using Godot;
using System.Collections.Generic;
using System.Linq;

// =================================================================================================
// FILE: Effect_UnhallowAura.cs
// PURPOSE: Container effect for Unhallow. Operates as a permanent aura OR a standalone cast spell.
// =================================================================================================
public enum TiedSpellTargetMode { AllCreatures, SameAlignment, OpposedAlignment }

[GlobalClass]
public partial class Effect_UnhallowAura : AbilityEffectComponent
{
    [ExportGroup("Aura Settings")]
    [Export] public float Radius = 40f;
    [Export] 
    [Tooltip("TRUE: Attaches permanently to the caster (Construct Aura). FALSE: Drops at AimPoint (Standalone Spell).")]
    public bool IsMobile = true; 

    [ExportGroup("Tied Spell Logic")]
    [Export] 
    [Tooltip("The registry list from which a spell is selected (Generated by the Editor Tool).")]
    public UnhallowTiedSpellList_SO AllowedSpellsList;
    
    [Export] 
    public TiedSpellTargetMode TargetMode = TiedSpellTargetMode.AllCreatures;

    [ExportGroup("Base Unhallow Buffs")]
    [Export] public StatusEffect_SO MagicCircleAgainstGoodEffect;
    [Export] public StatusEffect_SO ChannelResistanceEffect;

    public override void ExecuteEffect(EffectContext context, Ability_SO ability, Dictionary<CreatureStats, bool> targetSaveResults)
    {
        CreatureStats caster = context.Caster;
        if (caster == null) return;

        Ability_SO tiedSpell = null;

        // SCENARIO 1: Construct Aura (Randomly assigned at creation)
        if (IsMobile && caster.RuntimeTiedSpell != null)
        {
            tiedSpell = caster.RuntimeTiedSpell;
        }
        // SCENARIO 2: Player Casts Standalone Spell
        else if (!IsMobile && caster.IsInGroup("Player"))
        {
            // UI INTEGRATION HOOK:
            // When the player casts Unhallow, your UI should set caster.RuntimeTiedSpell 
            // BEFORE calling CombatManager.ResolveAbility().
            if (caster.RuntimeTiedSpell != null)
            {
                tiedSpell = caster.RuntimeTiedSpell;
                // Clear it after casting so they can choose a different one next time
                caster.RuntimeTiedSpell = null; 
            }
            else
            {
                GD.PrintErr("Player cast Unhallow but no Tied Spell was selected in the UI!");
                return;
            }
        }
        // SCENARIO 3: AI Casts Standalone Spell
        else if (!IsMobile && !caster.IsInGroup("Player"))
        {
            // AI picks a random beneficial spell from the list
            if (AllowedSpellsList != null && AllowedSpellsList.AllowedSpells.Count > 0)
            {
                var rng = new RandomNumberGenerator();
                rng.Randomize();
                tiedSpell = AllowedSpellsList.AllowedSpells[rng.RandiRange(0, AllowedSpellsList.AllowedSpells.Count - 1)];
            }
        }

        // --- SPAWN THE AURA ---
        // If mobile, anchor to creature. If standalone spell, anchor to the targeted ground.
        Node anchor = IsMobile ? (Node)caster : caster.GetTree().CurrentScene;
        Vector3 spawnPos = IsMobile ? Vector3.Zero : context.AimPoint;

        var auraObj = new Node3D { Name = "UnhallowAuraController" };
        anchor.AddChild(auraObj);
        auraObj.GlobalPosition = IsMobile ? caster.GlobalPosition : spawnPos;

        var controller = new UnhallowAuraController();
        controller.Name = "ControllerBehavior";
        auraObj.AddChild(controller);

        controller.Initialize(caster, ability, tiedSpell, Radius, TargetMode, MagicCircleAgainstGoodEffect, ChannelResistanceEffect);

        string spellName = tiedSpell != null ? tiedSpell.AbilityName : "None";
        string castType = IsMobile ? "emanates a permanent aura of" : "casts a standalone";
        GD.PrintRich($"[color=purple]{caster.Name} {castType} Unhallow! (Tied Spell: {spellName})[/color]");
    }

    public override float GetAIEstimatedValue(EffectContext context)
    {
        float baseValue = 100f; // Value of Magic Circle + Channel Modifiers
        return baseValue;
    }
}